# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'TapNetworkKit-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TapNetworkKit-iOS
pod 'TapAdditionsKitV2'
pod 'CommonDataModelsKit-iOS'
pod 'TapCardVlidatorKit-iOS'
pod 'SwiftyRSA'
pod 'TapApplicationV2'
end

target 'TapNetworkKit-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
end
